local keymap = vim.keymap.set

keymap("v", "<leader>v", [["+y]])

keymap("n", "<leader>tn", "<cmd>tabnew<CR>")
keymap("n", "<leader>tc", "<cmd>tabclose<CR>")
keymap("n", "<leader>p", "<cmd>tabprevious<CR>")
keymap("n", "<leader>n", "<cmd>tabnext<CR>")
keymap("n", "<A-Left>", function()
  vim.cmd(("silent! tabmove %d"):format(vim.fn.tabpagenr() - 2))
end, { silent = true })
keymap("n", "<A-Right>", function()
  vim.cmd(("silent! tabmove %d"):format(vim.fn.tabpagenr() + 1))
end, { silent = true })

keymap("n", "<leader>l", "<cmd>ls<CR>")
keymap("n", "<leader>b", "<cmd>bp<CR>")
keymap("n", "<leader>f", "<cmd>bn<CR>")
keymap("n", "<leader>bd", "<cmd>bp<bar>sp<bar>bn<bar>bd<CR>")
keymap("n", "<leader>g", "<cmd>e#<CR>")
keymap("n", "<leader>1", "<cmd>1b<CR>")
keymap("n", "<leader>2", "<cmd>2b<CR>")
keymap("n", "<leader>3", "<cmd>3b<CR>")
keymap("n", "<leader>4", "<cmd>4b<CR>")
keymap("n", "<leader>5", "<cmd>5b<CR>")
keymap("n", "<leader>6", "<cmd>6b<CR>")
keymap("n", "<leader>7", "<cmd>7b<CR>")
keymap("n", "<leader>8", "<cmd>8b<CR>")
keymap("n", "<leader>9", "<cmd>9b<CR>")
keymap("n", "<leader>0", "<cmd>10b<CR>")

keymap("n", "gp", "`[v`]")
keymap("x", "J", ":move '>+1<CR>gv=gv")
keymap("x", "K", ":move '<-2<CR>gv=gv")
keymap("n", "<leader>d", "<cmd>t.<CR>")
keymap("x", "<leader>d", ":t'><CR>gv")

keymap("n", "<leader><space>", "<cmd>nohlsearch<CR>")
keymap("n", "<leader>o", "<cmd>only<CR>")
keymap({ "n", "x" }, "+", "<C-a>")
keymap({ "n", "x" }, "-", "<C-x>")
keymap("x", "+", "g<C-a>")
keymap("x", "-", "g<C-x>")

keymap("n", "<C-n>", "<cmd>cnext<CR>")
keymap("n", "<C-m>", "<cmd>cprevious<CR>")
keymap("n", "<leader>qc", "<cmd>cclose<CR>")
keymap("n", "<space>", "za")

keymap("c", "w!!", "execute 'silent! write !sudo tee % >/dev/null' <bar> edit!")
